title:              Perivitta Rajendran
email:              peri_2704@hotmail.my
description:        AI Explorer's Journal :)
author:             PR-Peri
baseurl:            ""
url:                "https://PR_Web.github.io"

# Social Profiles
twitter_username:   
github_username:    PR-Peri
facebook_username:  
instagram_username:  
linkedin_username: perivitta-rajendran

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-N9BJNYKTCT # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
